# Boston house price


## 1 - Packages ##

Let's first import all the packages that you will need during this assignment.
- [tensorflow](https://www.tensorflow.org/) is the fundamental package for scientific computing with Python.
- [sklearn](http://scikit-learn.org/stable/) provides simple and efficient tools for data mining and data analysis. 
- [matplotlib](http://matplotlib.org) is a library for plotting graphs in Python.
- planar_utils provide various useful functions used in this assignment

In [1]:
# Import packages

import pandas as pd
import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import r2_score

---
## 2 - Dataset ##

The dataset describes 13 numerical properties of houses in Boston suburbs and is concerned with modeling the price of houses in those suburbs in thousands of dollars. As such, this is a regression predictive modeling problem. Input attributes include crime rate, the proportion of nonretail business acres, chemical concentrations, and more.

In [83]:
# load dataset
dataframe = pd.read_csv("housing.csv", delim_whitespace=True, header=None)
dataframe.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       506 non-null    float64
 1   1       506 non-null    float64
 2   2       506 non-null    float64
 3   3       506 non-null    int64  
 4   4       506 non-null    float64
 5   5       506 non-null    float64
 6   6       506 non-null    float64
 7   7       506 non-null    float64
 8   8       506 non-null    int64  
 9   9       506 non-null    float64
 10  10      506 non-null    float64
 11  11      506 non-null    float64
 12  12      506 non-null    float64
 13  13      506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


**Let's transform it into a numpy array, to work with just numbers fed to the dataframe**

In [84]:
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:13]
Y = dataset[:,13]

In [85]:
shape_X = X.shape
shape_Y = Y.shape
m = shape_X[0]  # training set size

print ('The shape of X is: ' + str(shape_X))
print ('The shape of Y is: ' + str(shape_Y))
print ('I have m = %d training examples!' % (m))

The shape of X is: (506, 13)
The shape of Y is: (506,)
I have m = 506 training examples!


**Split the data into train-test subsets**

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

---
## Build Basic model:

**Note the differences from the classification layer**

In [87]:
# create model
model = Sequential()

model.add(keras.Input(shape=(13)))
model.add(Dense(units=13,activation='relu',name='dense_2'))
model.add(Dense(units=1,name='dense_3'))

In [88]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 13)                182       
                                                                 
 dense_3 (Dense)             (None, 1)                 14        
                                                                 
Total params: 196 (784.00 Byte)
Trainable params: 196 (784.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Another way of building the ANN

In [89]:
# Build the model



In [90]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 13)                182       
                                                                 
 dense_3 (Dense)             (None, 1)                 14        
                                                                 
Total params: 196 (784.00 Byte)
Trainable params: 196 (784.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Now, Comile the model:

In [91]:
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.03),loss = 'mean_absolute_error')

**Fit the model**

In [92]:
# model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)
model.fit(X_train, y_train, batch_size=32, epochs=100, verbose=1)

Epoch 1/100


13/13 [==============================] - 9s 19ms/step - loss: 76.3269
Epoch 2/100
13/13 [==============================] - 0s 21ms/step - loss: 18.3412
Epoch 3/100
13/13 [==============================] - 0s 24ms/step - loss: 9.2100
Epoch 4/100
13/13 [==============================] - 0s 22ms/step - loss: 7.2615
Epoch 5/100
13/13 [==============================] - 0s 17ms/step - loss: 6.4488
Epoch 6/100
13/13 [==============================] - 0s 18ms/step - loss: 6.2813
Epoch 7/100
13/13 [==============================] - 0s 20ms/step - loss: 6.1027
Epoch 8/100
13/13 [==============================] - 0s 19ms/step - loss: 5.8916
Epoch 9/100
13/13 [==============================] - 0s 21ms/step - loss: 5.1517
Epoch 10/100
13/13 [==============================] - 0s 13ms/step - loss: 5.4338
Epoch 11/100
13/13 [==============================] - 0s 25ms/step - loss: 5.3998
Epoch 12/100
13/13 [==============================] - 0s 18ms/step - loss: 5.2229
Epoch 13/100
13/13 [===============

**Print model evaluation**

In [93]:
model.evaluate(X_train, y_train, batch_size=32, verbose=1)


13/13 [==============================] - 5s 21ms/step - loss: 3.7983


3.7982616424560547

**Calculate the R-Squared score for the model**

In [94]:
y_predicted = model.predict(X_test)
y_predicted[0]

4/4 [==============================] - 1s 12ms/step


array([26.559778], dtype=float32)

In [95]:
r2_score(y_test, y_predicted)

0.6969222012215761

Reasonable performance for models evaluated using Mean Squared Error (MSE) is around 20 in thousands of dollars squared (or $4,500 if you take the square root). This is a nice target to aim for with our neural network model.


___
## Trying scaling data:

In [96]:
# Try the scaling with StandardScaling
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [97]:
# create model
model = Sequential()

model.add(keras.Input(shape=(13)))
model.add(Dense(units=13,activation='relu',name='dense_2'))
model.add(Dense(units=1,name='dense_3'))

In [98]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 13)                182       
                                                                 
 dense_3 (Dense)             (None, 1)                 14        
                                                                 
Total params: 196 (784.00 Byte)
Trainable params: 196 (784.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [99]:


model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.03),loss = 'mean_absolute_error')


In [100]:
# model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)
model.fit(X_train, y_train, batch_size=16, epochs=75, verbose=1)

Epoch 1/75


26/26 [==============================] - 10s 44ms/step - loss: 17.9038
Epoch 2/75
26/26 [==============================] - 1s 58ms/step - loss: 6.5193
Epoch 3/75
26/26 [==============================] - 1s 44ms/step - loss: 4.2600
Epoch 4/75
26/26 [==============================] - 1s 25ms/step - loss: 3.6666
Epoch 5/75
26/26 [==============================] - 0s 14ms/step - loss: 3.0816
Epoch 6/75
26/26 [==============================] - 0s 12ms/step - loss: 3.0508
Epoch 7/75
26/26 [==============================] - 0s 10ms/step - loss: 2.7399
Epoch 8/75
26/26 [==============================] - 0s 11ms/step - loss: 2.5361
Epoch 9/75
26/26 [==============================] - 0s 13ms/step - loss: 2.5513
Epoch 10/75
26/26 [==============================] - 0s 10ms/step - loss: 2.4970
Epoch 11/75
26/26 [==============================] - 0s 10ms/step - loss: 2.6153
Epoch 12/75
26/26 [==============================] - 0s 11ms/step - loss: 2.3379
Epoch 13/75
26/26 [===========================

**Print model evaluation**

In [101]:
model.evaluate(X_train, y_train, batch_size=32, verbose=1)

13/13 [==============================] - 1s 16ms/step - loss: 1.6481


1.6480976343154907

In [102]:
model.evaluate(X_test, y_test, batch_size=32, verbose=1)

4/4 [==============================] - 1s 8ms/step - loss: 2.2930


2.2929890155792236

**Calculate the R-Squared score for the model**

In [103]:
y_predicted = model.predict(X_test)
y_predicted[0]

4/4 [==============================] - 0s 10ms/step


array([25.136093], dtype=float32)

In [104]:
r2_score(y_test, y_predicted)

0.8412980556180473

---
## Build a deeper model:

In [ ]:
# create model




In [ ]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 13)                182       
                                                                 
 dense_7 (Dense)             (None, 6)                 84        
                                                                 
 dense_8 (Dense)             (None, 1)                 7         
                                                                 
Total params: 273
Trainable params: 273
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)
model.fit(X_train, y_train, batch_size=5, epochs=50, verbose=0)

**Print model evaluation**

In [ ]:
model.evaluate(X_train, y_train, batch_size=32, verbose=1)

13/13 [==============================] - 0s 2ms/step - loss: 7.8861 - mean_squared_error: 7.8861


[7.886094570159912, 7.886094570159912]

In [ ]:
model.evaluate(X_test, y_test, batch_size=32, verbose=1)

4/4 [==============================] - 0s 3ms/step - loss: 11.6247 - mean_squared_error: 11.6247


[11.624679565429688, 11.624679565429688]

**Calculate the R-Squared score for the model**

In [ ]:
y_predicted = model.predict(X_test)
y_predicted[0]

4/4 [==============================] - 0s 2ms/step


array([23.989002], dtype=float32)

In [ ]:
r2_score(y_test, y_predicted)

0.8343883345278527

---
## try MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
X_train = 
X_test = 

In [ ]:
# create model




In [ ]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 13)                182       
                                                                 
 dense_15 (Dense)            (None, 6)                 84        
                                                                 
 dense_16 (Dense)            (None, 1)                 7         
                                                                 
Total params: 273
Trainable params: 273
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)
model.fit(X_train, y_train, batch_size=5, epochs=50, verbose=0)

**Print model evaluation**

In [ ]:
model.evaluate(X_train, y_train, batch_size=32, verbose=1)

13/13 [==============================] - 0s 1ms/step - loss: 11.0666 - mean_squared_error: 11.0666


[11.066582679748535, 11.066582679748535]

In [ ]:
model.evaluate(X_test, y_test, batch_size=32, verbose=1)

4/4 [==============================] - 0s 3ms/step - loss: 12.1449 - mean_squared_error: 12.1449


[12.144929885864258, 12.144929885864258]

**Calculate the R-Squared score for the model**

In [ ]:
y_predicted = model.predict(X_test)
y_predicted[0]

4/4 [==============================] - 0s 2ms/step


array([23.989002], dtype=float32)

In [ ]:
r2_score(y_test, y_predicted)

0.8343883345278527

---
## Try a wider model**

In [ ]:
# create model




In [ ]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 20)                280       
                                                                 
 dense_13 (Dense)            (None, 1)                 21        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1)
model.fit(X_train, y_train, batch_size=5, epochs=50, verbose=0)

**Print model evaluation**

In [ ]:
model.evaluate(X_train, y_train, batch_size=32, verbose=1)

13/13 [==============================] - 0s 2ms/step - loss: 8.3818 - mean_squared_error: 8.3818


[8.381789207458496, 8.381789207458496]

In [ ]:
model.evaluate(X_test, y_test, batch_size=32, verbose=1)

4/4 [==============================] - 0s 3ms/step - loss: 11.7419 - mean_squared_error: 11.7419


[11.741930961608887, 11.74193000793457]

**Calculate the R-Squared score for the model**

In [ ]:
y_predicted = model.predict(X_test)
y_predicted[0]

4/4 [==============================] - 0s 2ms/step


array([23.989002], dtype=float32)

In [ ]:
r2_score(y_test, y_predicted)

0.8343883345278527